service: 'service-017-serverless-dynamodb'
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ProductsTable.Arn

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    target: node20
    platform: node
    concurrency: 10
  
functions:
  listProduct:
    handler: src/functions/list-products.handler
    events:
      - httpApi:
          path: /products
          method: GET
  getProduct:
    handler: src/functions/get-product.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: GET
  createProduct:
    handler: src/functions/create-product.handler
    events:
      - httpApi:
          path: /products
          method: POST
  updateProduct:
    handler: src/functions/update-product.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: PUT
  deleteProduct:
    handler: src/functions/delete-product.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: DELETE

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH